### ISSUE TITLE
Specify login user with tag

### ISSUE THREAD

**Issue by mmindenhall** [peh/node-i2cssh#3]
Very cool project!

All of my companies EC2 instances are running ubuntu, so I need to ssh as the `ubuntu` user instead of myself.  I tried using this option (as documented in [original i2cssh](https://github.com/wouterdebie/i2cssh), but it didn't work:

```
-l, --login LOGIN                SSH login name
```

Would it be possible to implement this flag (or equivalent)?  The behavior I want to have happen is:

1. `$ envchain aws i2cssh -l ubuntu -t`
1. select tag key
1. select tag value
1. i2cssh generates `ssh ubuntu@ec2-whatever.amazonaws.com` in each terminal session

**Comment by peh** [comment]
yes. will put it on the agenda. should be farily easy to realize

**Comment by peh** [comment]
released 1.6.0 to npm. have fun
